// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "../../components/ui/Input.res.js";
import * as React from "react";
import * as UseDebounce from "../../hooks/UseDebounce.res.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as FetchUtils from "../../lib/fetch-utils";
import * as ReactQuery from "@tanstack/react-query";

function fetchData(prim) {
  return FetchUtils.fetchData(prim);
}

function RescriptPostSearch(props) {
  let match = React.useState(() => "");
  let setSearchTerm = match[1];
  let searchTerm = match[0];
  let debouncedSearchTerm = UseDebounce.use(searchTerm, 500);
  let match$1 = ReactQuery.useQuery({
    queryKey: [
      "posts",
      "search",
      debouncedSearchTerm
    ],
    queryFn: param => FetchUtils.fetchData("/api/posts/search?search=" + debouncedSearchTerm),
    enabled: debouncedSearchTerm.length > 0
  });
  let data = match$1.data;
  React.useEffect(() => {
    console.log("!!!!!searchTerm", searchTerm);
  }, [searchTerm]);
  React.useEffect(() => {
    console.log("!!!!!debouncedSearchTerm", debouncedSearchTerm);
  }, [debouncedSearchTerm]);
  React.useEffect(() => {
    console.log("!!!!!data", data);
  }, [data]);
  let match$2 = debouncedSearchTerm.length === 0;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(Input.make, {
            className: "w-full",
            type_: "text",
            placeholder: "Search posts...",
            value: searchTerm,
            onChange: e => setSearchTerm(param => e.target.value)
          }),
          JsxRuntime.jsx("button", {
            children: "Clear",
            className: "bg-gray-200 p-2 rounded",
            disabled: searchTerm.length === 0,
            onClick: param => setSearchTerm(param => "")
          })
        ],
        className: "flex gap-2"
      }),
      match$2 ? JsxRuntime.jsx("p", {
          children: "Start typing to search...",
          className: "p-4 text-center text-gray-500 border border-dashed rounded-md"
        }) : (
          match$1.isLoading ? JsxRuntime.jsx("p", {
              children: "Loading posts...",
              className: "mb-4 text-blue-500"
            }) : (
              match$1.isError ? (console.log("error", match$1.error), JsxRuntime.jsx("p", {
                  children: "Error: ",
                  className: "mb-4 text-red-500"
                })) : (
                  data !== undefined ? (
                      data.length === 0 ? JsxRuntime.jsx("p", {
                          children: "No posts found",
                          className: "mb-4 "
                        }) : JsxRuntime.jsx("ul", {
                          children: data.map(post => JsxRuntime.jsxs("li", {
                            children: [
                              JsxRuntime.jsx("h3", {
                                children: post.title,
                                className: "font-semibold"
                              }),
                              JsxRuntime.jsx("p", {
                                children: post.body
                              })
                            ],
                            className: "border p-3 rounded"
                          }, post.id.toString())),
                          className: "space-y-4"
                        })
                    ) : JsxRuntime.jsx("p", {
                      children: "Something went wrong",
                      className: "mb-4 bg-red-100"
                    })
                )
            )
        )
    ],
    className: "space-y-4"
  });
}

let make = RescriptPostSearch;

export {
  fetchData,
  make,
}
/* Input Not a pure module */
