// Generated by ReScript, PLEASE EDIT WITH CARE


function newCommentToJSON(newComment) {
  let dict = {};
  dict["text"] = newComment.text;
  return dict;
}

export {
  newCommentToJSON,
}
/* No side effect */
