// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FetchUtils from "../../lib/fetch-utils";
import * as ReactQuery from "@tanstack/react-query";

function fetchData(prim) {
  return FetchUtils.fetchData(prim);
}

let queryKey = ["comments"];

function useCommentsQuery() {
  let queryFn = params => {
    console.log("___________params", params);
    console.log("________pageParam", params.pageParam);
    let pageNumber = params.pageParam;
    let cursorArgument = pageNumber !== undefined ? "cursor=" + pageNumber.toString() : "";
    console.log("cursorArgument", cursorArgument);
    return FetchUtils.fetchData("/api/comments?" + cursorArgument);
  };
  return ReactQuery.useInfiniteQuery({
    queryKey: queryKey,
    queryFn: queryFn,
    initialPageParam: 0,
    getNextPageParam: lastPage => lastPage.nextCursor
  });
}

export {
  fetchData,
  queryKey,
  useCommentsQuery,
}
/* ../../lib/fetch-utils Not a pure module */
