// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptInfiniteComments_Form from "./RescriptInfiniteComments_Form.res.js";
import * as RescriptInfiniteComments_UseComments from "./RescriptInfiniteComments_UseComments.res.js";

function RescriptInfiniteComments(props) {
  let match = RescriptInfiniteComments_UseComments.useCommentsQuery();
  let fetchNextPage = match.fetchNextPage;
  let isFetchingNextPage = match.isFetchingNextPage;
  let data = match.data;
  let isError = match.isError;
  let comments = data !== undefined ? (console.log("response pageParams", data.pageParams), console.log("response pages", data.pages), data.pages.flatMap(page => page.comments)) : (console.log("~~~~ data is NONE"), []);
  let match$1 = comments.length === 0;
  let tmp;
  let exit = 0;
  if (match.isLoading) {
    if (isError) {
      tmp = JsxRuntime.jsx("p", {
        children: "Loading posts...",
        className: "mb-4 text-blue-500"
      });
    } else {
      exit = 1;
    }
  } else if (isError) {
    console.log("error", match.error);
    tmp = JsxRuntime.jsx("p", {
      children: "Error Loading comments: ",
      className: "mb-4 text-red-500"
    });
  } else if (match$1) {
    tmp = JsxRuntime.jsx("p", {
      children: "No comments yet.",
      className: "mb-4 bg-blue-50"
    });
  } else {
    exit = 1;
  }
  if (exit === 1) {
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: comments.map(comment => JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("div", {
                  children: comment.user.avatar,
                  className: "w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center text-sm font-medium"
                }),
                className: "flex-shrink-0"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("p", {
                        children: comment.user.name,
                        className: "font-medium"
                      }),
                      JsxRuntime.jsx("span", {
                        children: comment.createdAt,
                        className: "text-xs text-gray-500"
                      })
                    ],
                    className: "flex justify-between items-start"
                  }),
                  JsxRuntime.jsx("p", {
                    children: comment.text,
                    className: "text-gray-700 mt-1"
                  })
                ],
                className: "flex-1"
              })
            ],
            className: "flex gap-3 p-3 border rounded-lg bg-white"
          }, comment.id.toString())),
          className: "space-y-3"
        }),
        JsxRuntime.jsx("div", {
          children: match.hasNextPage ? JsxRuntime.jsx("button", {
              children: isFetchingNextPage ? "Loading more..." : "Load More Comments",
              className: "px-4 py-2 bg-gray-600 text-white rounded-lg ",
              disabled: isFetchingNextPage,
              onClick: param => fetchNextPage()
            }) : null,
          className: "flex justify-center my-4"
        })
      ]
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h2", {
        children: "Comments ",
        className: "text-xl font-bold mb-4"
      }),
      JsxRuntime.jsx(RescriptInfiniteComments_Form.make, {}),
      tmp
    ],
    className: ""
  });
}

let make = RescriptInfiniteComments;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
