// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Comment from "./Comment.res.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as FetchUtils from "../../lib/fetch-utils";
import * as ReactQuery from "@tanstack/react-query";

function postData(prim0, prim1) {
  return FetchUtils.postData(prim0, prim1);
}

let queryKey = ["comments"];

function useCreateCommentMutationOptimistic() {
  let queryClient = ReactQuery.useQueryClient();
  return ReactQuery.useMutation({
    mutationKey: [
      "my",
      "mutation"
    ],
    mutationFn: newComment => FetchUtils.postData("/api/comments", Comment.newCommentToJSON(newComment)),
    onMutate: async newCommentData => {
      await queryClient.cancelQueries({
        queryKey: Primitive_option.some(queryKey)
      });
      queryClient.getQueryData(queryKey);
      Date.now() | 0;
      newCommentData.text;
      new Date().toUTCString();
      return queryClient.setQueryData(queryKey, undefined);
    },
    onError: (error, variables, context) => {
      console.log("onError context", context);
      if (!(context == null)) {
        console.log("context", context);
        "none";
      }
      return Promise.resolve(42);
    }
  });
}

export {
  postData,
  queryKey,
  useCreateCommentMutationOptimistic,
}
/* ../../lib/fetch-utils Not a pure module */
