// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "../../components/ui/Input.res.js";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptInfiniteComments_UseComments_Optimistic from "./RescriptInfiniteComments_UseComments_Optimistic.res.js";

function RescriptInfiniteComments_Form(props) {
  let match = React.useState(() => "");
  let setCommentText = match[1];
  let commentText = match[0];
  let commentTextIsEmpty = commentText.trim().length === 0;
  let mutation = RescriptInfiniteComments_UseComments_Optimistic.useCreateCommentMutationOptimistic();
  React.useEffect(() => {
    console.log("!!!!!commentText", commentText);
  }, [commentText]);
  let handleSubmit = e => {
    e.preventDefault();
    if (commentTextIsEmpty) {
      return;
    }
    let mutationVariables = {
      text: commentText
    };
    mutation.mutate(mutationVariables, {
      onSuccess: (a, b, c) => {
        setCommentText(param => "");
        console.log("Comment posted successfully!");
        return Promise.resolve(42);
      },
      onError: (a, b, c) => {
        console.error("Failed to post comment. Please try again.");
        return Promise.resolve(-1);
      },
      onSettled: (a, b, c, d) => {
        console.log("onSettled");
        return Promise.resolve(0);
      }
    });
  };
  return JsxRuntime.jsxs("form", {
    children: [
      JsxRuntime.jsx(Input.make, {
        className: "flex-1",
        type_: "text",
        placeholder: "Add a comment...",
        value: commentText,
        onChange: e => setCommentText(param => e.target.value),
        disabled: false
      }),
      JsxRuntime.jsx("button", {
        children: "Post",
        className: "px-4 py-2 bg-slate-500 text-white rounded-lg ",
        disabled: commentTextIsEmpty,
        type: "submit"
      })
    ],
    className: "flex gap-2 mb-6",
    onSubmit: handleSubmit
  });
}

let make = RescriptInfiniteComments_Form;

export {
  make,
}
/* Input Not a pure module */
