// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function use(value, delay) {
  let match = React.useState(() => value);
  let setDebouncedValue = match[1];
  React.useEffect(() => {
    let timer = setTimeout(() => setDebouncedValue(param => value), delay);
    return () => {
      clearTimeout(timer);
    };
  }, [
    value,
    delay
  ]);
  return match[0];
}

export {
  use,
}
/* react Not a pure module */
