// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RescriptQuery from "../../rescript-query/RescriptQuery.res.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as FetchUtils from "../../lib/fetch-utils";
import * as ReactQuery from "@tanstack/react-query";

function fetchData(prim) {
  return FetchUtils.fetchData(prim);
}

function FetchWithRescriptQuery(props) {
  let category = props.category;
  let match = ReactQuery.useQuery({
    queryKey: [
      "posts",
      category
    ],
    queryFn: param => FetchUtils.fetchData("/api/posts?category=" + category),
    refetchOnWindowFocus: Primitive_option.some(RescriptQuery.TanstackQuery_Utils.refetchOnWindowFocus({
      NAME: "bool",
      VAL: true
    }))
  });
  let data = match.data;
  console.log("data", data);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h2", {
        children: category + " Posts",
        className: "text-xl font-bold mb-4"
      }),
      match.isLoading ? JsxRuntime.jsx("p", {
          children: "Loading posts...",
          className: "mb-4 text-blue-500"
        }) : (
          match.isError ? (console.log("error", match.error), JsxRuntime.jsx("p", {
              children: "Error: ",
              className: "mb-4 text-red-500"
            })) : (
              data !== undefined ? (
                  data.length === 0 ? JsxRuntime.jsx("p", {
                      children: "No posts found",
                      className: "mb-4 "
                    }) : JsxRuntime.jsx("ul", {
                      children: data.map(post => JsxRuntime.jsxs("li", {
                        children: [
                          JsxRuntime.jsx("h3", {
                            children: post.title,
                            className: "font-semibold"
                          }),
                          JsxRuntime.jsx("p", {
                            children: post.body
                          })
                        ],
                        className: "border p-3 rounded"
                      }, post.id.toString())),
                      className: "space-y-4"
                    })
                ) : JsxRuntime.jsx("p", {
                  children: "Something went wrong",
                  className: "mb-4 bg-red-100"
                })
            )
        )
    ],
    className: "p-4"
  });
}

let make = FetchWithRescriptQuery;

export {
  fetchData,
  make,
}
/* react/jsx-runtime Not a pure module */
