// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "rescript/lib/es6/Pervasives.js";

let Provider = {};

let TanstackQuery_Client = {
  Provider: Provider
};

let TanstackQuery_Hooks = {};

let TanstackQuery_InfiniteQuery = {};

let TanstackQuery_Mutation = {};

let TanstackQuery_Query = {};

function retry(value) {
  return value.VAL;
}

function retryDelay(value) {
  return value.VAL;
}

function time(value) {
  if (typeof value === "object") {
    return value.VAL;
  } else {
    return Pervasives.infinity;
  }
}

function refetchInterval(value) {
  return value.VAL;
}

function boolOrAlways(value) {
  if (typeof value === "object") {
    return value.VAL;
  } else {
    return "always";
  }
}

function notifyOnChangeProps(value) {
  if (typeof value === "object") {
    return value.VAL;
  } else {
    return "tracked";
  }
}

function setQueryData(value) {
  return value.VAL;
}

function placeholderData(value) {
  return value.VAL;
}

let TanstackQuery_Utils = {
  retry: retry,
  retryDelay: retryDelay,
  time: time,
  refetchInterval: refetchInterval,
  boolOrAlways: boolOrAlways,
  notifyOnChangeProps: notifyOnChangeProps,
  setQueryData: setQueryData,
  placeholderData: placeholderData,
  refetchOnMount: boolOrAlways,
  refetchOnWindowFocus: boolOrAlways,
  refetchOnReconnect: boolOrAlways
};

let DevTools = {};

let Client;

let Hooks;

let InfiniteQuery;

let Mutation;

let Utils;

export {
  TanstackQuery_Client,
  TanstackQuery_Hooks,
  TanstackQuery_InfiniteQuery,
  TanstackQuery_Mutation,
  TanstackQuery_Query,
  TanstackQuery_Utils,
  Client,
  Hooks,
  InfiniteQuery,
  Mutation,
  Utils,
  DevTools,
}
/* No side effect */
